"""The published tools catalog lists every tool Kazma registers, labelled right.

``docs/docs/reference/tools-catalog.md`` is generated by
``scripts/generate_tools_catalog.py``. Until 2026-09-25 the generator
regex-scanned ``agent/tool_builtins.py`` for ``@registry.register``
decorators, but that module had long been split into a package registering
with ``register_function(...)``: the scan found 1 built-in tool, a run would
have deleted ~70 rows, and the catalog was maintained by hand — about 20
registered tools were missing from it, and its Danger column called
danger-tier tools such as ``send_file`` "safe/read".

The generator now reads the live registry. These gates fail when a
registered tool is missing from the committed catalog, when a tool is listed
twice, or when the catalog's danger label disagrees with the approval gate.
Fix by running ``python scripts/generate_tools_catalog.py``.
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "docs" / "docs" / "reference" / "tools-catalog.md"

#: A table row whose FIRST cell is a backticked tool name — not a prose
#: mention and not the bullet list of danger tools at the end.
_ROW = re.compile(r"^\|\s*`([A-Za-z0-9_]+)`\s*\|(.*)$", re.MULTILINE)


def _catalog_rows(text: str) -> dict[str, list[str]]:
    rows: dict[str, list[str]] = {}
    for name, rest in _ROW.findall(text):
        rows.setdefault(name, []).append(rest)
    return rows


def _missing_from_catalog(registered: set[str], catalog_text: str) -> list[str]:
    return sorted(registered - set(_catalog_rows(catalog_text)))


def _registered() -> set[str]:
    from kazma_core.agent.tool_builtins import register_builtin_tools
    from kazma_core.agent.tool_registry import LocalToolRegistry

    registry = LocalToolRegistry()
    register_builtin_tools(registry)
    return set(registry._tools)


def _generator():
    spec = importlib.util.spec_from_file_location(
        "generate_tools_catalog", ROOT / "scripts" / "generate_tools_catalog.py"
    )
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def test_every_registered_tool_is_in_the_catalog():
    missing = _missing_from_catalog(_registered(), CATALOG.read_text(encoding="utf-8"))
    assert not missing, (
        "Registered tools missing from docs/docs/reference/tools-catalog.md.\n"
        "Run: python scripts/generate_tools_catalog.py\n  " + ", ".join(missing)
    )


def test_a_tool_missing_from_the_catalog_is_caught():
    """Negative control: a registered tool with no row is reported, and a
    prose mention or a bullet in the danger list does not count as a row."""
    catalog = (
        "| `file_read` | filesystem | safe/read | Read a file. |\n"
        "| `file_write` | filesystem | **danger** | Write a file. |\n"
        "Read drafts back with `list_proposals`.\n"
        "- `list_proposals`\n"
    )
    assert _missing_from_catalog({"file_read", "file_write", "list_proposals"}, catalog) == [
        "list_proposals"
    ]


def test_no_tool_is_listed_twice():
    """Native skill tools are registered in the same registry as built-ins;
    they belong in the native section only."""
    doubled = sorted(
        name for name, rows in _catalog_rows(CATALOG.read_text(encoding="utf-8")).items()
        if len(rows) > 1
    )
    assert not doubled, f"listed more than once: {doubled}"


def test_the_generator_reads_the_live_registry():
    gen = _generator()
    builtin = {t["name"] for t in gen.extract_builtin()}
    native = {t["name"] for t in gen.extract_native()}
    assert not builtin & native, sorted(builtin & native)
    registered = _registered()
    assert registered <= builtin | native, (
        "the generator would leave registered tools out: "
        + ", ".join(sorted(registered - builtin - native))
    )
    # The stale source scan found exactly one of these.
    assert {"file_read", "memory_search", "save_proposal", "list_proposals"} <= builtin


def test_the_danger_label_matches_the_approval_gate():
    """A catalog that calls an approval-gated tool safe misleads the operator.

    Checked against ``requires_approval`` under the shipped configuration,
    not against the generator's own table.
    """
    from kazma_core.safety.hitl import get_hitl_config, requires_approval

    cfg = get_hitl_config({})
    wrong = []
    for name, rows in _catalog_rows(CATALOG.read_text(encoding="utf-8")).items():
        gated = requires_approval(name, cfg)
        labelled = "**danger**" in rows[0]
        if gated != labelled:
            wrong.append(f"{name}: gate={'approval' if gated else 'none'}, catalog={'danger' if labelled else 'safe/read'}")
    assert not wrong, (
        "Danger labels that disagree with the approval gate — run "
        "python scripts/generate_tools_catalog.py:\n  " + "\n  ".join(sorted(wrong))
    )
