"""Every file the docs name is a file in this repository.

The docs cite source files in code spans -- `sse_chat.py`, `routes_direct.py:454`
-- and nothing checked that they still exist. On 2026-10-01 about forty named
files that were gone: modules that became packages (`sse_chat/`,
`routes_direct/`, `swarm_panel/`, `i18n/`, `tracing/`), modules removed as
orphans, a tokenizer whose normalization the Arabic guide still described step
by step, a `services.yaml` deleted in July with a configuration section of its
own, and -- in the security guide -- a delegation signing and encryption
layer (Ed25519, X25519 + AES-256-GCM) presented as a protection although its
archived code had been deleted two months earlier.

The pages checked are the docs under docs/docs and every other page kazma.ai
publishes (docs/website-pages.json). A name passes when a tracked file ends
with it (``a/.../b.py`` elides folders; a leading ``./`` and a ``:line``
suffix are ignored), or when it is declared below: a file Kazma or the
operator creates at runtime, an example, a file of another program or
repository, or a page's deliberate mention of a removed module. A module that
became a package is reported with the package to name instead.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs" / "docs"

_CODE_SPAN = re.compile(r"`([^`\n]+)`")
_FILE_REF = re.compile(
    r"(?<![\w.*-])((?:\.{1,2}/)?(?:[\w.-]+/|\.\.\./)*[\w-]+\.(?:py|mjs|js|html|css|json|yaml|yml|toml|ps1|sh))"
    r"(?::\d+(?:-\d+)?)?(?![\w/*])"
)
_FENCE = re.compile(r"^\s*(`{3,}|~{3,})(.*)$")

#: Names that are not files of this repository, and why.
NOT_REPOSITORY_FILES = {
    # created at runtime, by Kazma or the operator
    "swarm_registry.json": "the swarm's worker registry, written at runtime (git-ignored)",
    "kazma-data/update-state.json": "written by kazma update",
    "kazma-data/vuln_cache.json": "written by the dependency audit",
    "agent_evolution.json": "the pre-ConfigStore Soul file; migrated and renamed at boot",
    "metrics.json": "generated by scripts/generate_metrics.py",
    "plan.json": "a research session's working file",
    "sources.json": "a research session's working file",
    "claims.json": "a research session's working file",
    "gap_loop_0.json": "a research session's working file",
    "rubric.json": "a research session's working file",
    "config.yaml": "a migration bundle's settings file",
    "manifest.json": "a migration bundle's or a document job's manifest",
    "pathmap.json": "a migration bundle's path map",
    "rules.yaml": "created in a project by kazma project init",
    "personality.yaml": "created in a project by kazma project init",
    "tools.yaml": "created in a project by kazma project init",
    "Activate.ps1": "a virtual environment's activation script",
    "settings.json": "an editor's settings file",
    ".config/zed/settings.json": "Zed's settings file",
    "claude_desktop_config.json": "Claude Desktop's settings file",
    "ruleset.json": "a GitHub ruleset export",
    "_pytest/capture.py": "pytest's own module, in a crash's stack",
    # examples
    "my_skill.py": "an example skill",
    "kazma-skills/manifests/my-skill/skill_manifest.yaml": "an example skill's manifest",
    "manifest.yaml": "a skill manifest's accepted name",
    "manifest.yml": "a skill manifest's accepted name",
    "ar.json": "named to say there are no such files",
    "en.json": "named to say there are no such files",
    # API paths that end in .json
    "start.json": "an OAuth route (/api/.../start.json)",
    "api/calendar/oauth/microsoft/start.json": "an OAuth route",
    # the website's repository (Mubder/KazmaAI)
    "src/data/metrics.json": "kazma.ai's file",
    "src/data/docs-sync.json": "kazma.ai's file",
    "src/plugins/check-internal-links.mjs": "kazma.ai's file",
    "src/plugins/remark-heading-ids.mjs": "kazma.ai's file",
    "scripts/sync_from_kazma.py": "kazma.ai's retired port script, named as one not to reuse",
    "kazma/scripts/website_sync_plan.py": "this repository's script, seen from beside it",
}

#: A page naming a module that is gone, to say so: (page, name) -> why.
REMOVED_AND_SAID_SO = {
    ("docs/docs/guide/gateways-and-platforms.md", "agent_handler.py"): "says the file became a package",
    ("docs/docs/guide/glossary.md", "agent_handler.py"): "says the file became a package",
    ("docs/docs/guide/glossary.md", "swarm/memory/adapter.py"): "an entry for the removed V1 memory",
    ("docs/docs/guide/glossary.md", "memory/vector_store.py"): "an entry for the removed V1 memory",
    ("docs/docs/guide/skills-mcp-and-tools.md", "kazma_core/hub/api.py"): "says the hub API was removed",
    ("docs/docs/contributing/testing.md", "crawl.py"): "the deletion incident behind the import gate",
    ("docs/KNOWN_GAPS.md", "tool_builtins.py"): "the pre-split module an old catalog generator read",
}


def _tracked() -> list[str]:
    out = subprocess.run(["git", "-C", str(REPO), "ls-files"], capture_output=True,
                         text=True, encoding="utf-8", check=True).stdout
    return out.splitlines()


def published_pages() -> list[Path]:
    """docs/docs, and every page kazma.ai publishes from elsewhere."""
    manifest = json.loads((REPO / "docs" / "website-pages.json").read_text(encoding="utf-8"))
    pages = set(DOCS.rglob("*.md*"))
    pages.update(REPO / e["source"] for e in manifest["pages"] if e.get("site"))
    return sorted(p for p in pages if p.is_file())


def _prose(text: str):
    fence = None
    for line in text.splitlines():
        m = _FENCE.match(line)
        if fence is None:
            if m and not (m.group(1)[0] == "`" and "`" in m.group(2)):
                fence = (m.group(1)[0], len(m.group(1)))
                continue
            yield line
        elif m and m.group(1)[0] == fence[0] and len(m.group(1)) >= fence[1] \
                and not m.group(2).strip():
            fence = None


def _refs(page: Path):
    for line in _prose(page.read_text(encoding="utf-8")):
        for span in _CODE_SPAN.findall(line):
            for m in _FILE_REF.finditer(span):
                ref = m.group(1)
                yield ref[2:] if ref.startswith("./") else ref


def missing_files(pages: list[Path], root: Path, tracked: list[str]) -> list[str]:
    """``page: name`` for each file name no tracked file answers."""
    names = {f.rsplit("/", 1)[-1] for f in tracked}

    def became_package(ref: str) -> bool:
        """``x/name.py`` whose ``x/name/`` package is tracked."""
        folder = "/" + ref[: -len(".py")] + "/"
        return ref.endswith(".py") and any(folder in "/" + f for f in tracked)

    found = []
    for page in pages:
        rel = page.relative_to(root).as_posix()
        for ref in _refs(page):
            if ref in NOT_REPOSITORY_FILES or (rel, ref) in REMOVED_AND_SAID_SO:
                continue
            if "/" in ref:
                head, _, tail = ref.partition("/.../")
                if tail:
                    ok = any(f.startswith(head + "/") and f.endswith("/" + tail) for f in tracked)
                else:
                    ok = any(f == ref or f.endswith("/" + ref) for f in tracked)
            else:
                ok = ref in names
            if not ok:
                hint = f" (a package now: {ref[:-3]}/)" if became_package(ref) else ""
                found.append(f"{rel}: {ref}{hint}")
    return found


def test_every_file_the_docs_name_exists():
    assert missing_files(published_pages(), REPO, _tracked()) == []


def test_a_missing_file_is_found(tmp_path):
    """The negative control, and what passes."""
    (tmp_path / "guide").mkdir()
    (tmp_path / "guide" / "a.md").write_text(
        "# A\n\n"
        "`kazma_ui/sse_chat.py` and `sse_chat.py:353` and `gone.py` and `app.py:12`\n"
        "`./scripts/start.sh` `kazma-ui/.../app.py` `adapters/*_bus.py` `swarm_registry.json`\n"
        "```text\n`also_gone.py` in a code block is an example\n```\n",
        encoding="utf-8")
    (tmp_path / "guide" / "b.md").write_text("`delegation/security.py`\n", encoding="utf-8")
    tracked = ["kazma-ui/kazma_ui/app.py", "kazma-ui/kazma_ui/sse_chat/__init__.py",
               "scripts/start.sh", "kazma-gateway/kazma_gateway/adapters/slack_bus.py",
               "kazma-core/kazma_core/security/vault.py"]
    pages = sorted(tmp_path.rglob("*.md"))
    assert missing_files(pages, tmp_path, tracked) == [
        "guide/a.md: kazma_ui/sse_chat.py (a package now: kazma_ui/sse_chat/)",
        "guide/a.md: sse_chat.py (a package now: sse_chat/)",
        "guide/a.md: gone.py",
        "guide/b.md: delegation/security.py",  # an unrelated security/ is no package of it
    ]


def test_every_declaration_is_still_needed():
    """A declared name no page names any more leaves the lists."""
    cited: set = set()
    for page in published_pages():
        rel = page.relative_to(REPO).as_posix()
        for ref in _refs(page):
            cited.add(ref)
            cited.add((rel, ref))
    unused = sorted(str(k) for k in [*NOT_REPOSITORY_FILES, *REMOVED_AND_SAID_SO] if k not in cited)
    assert unused == []
