"""Phase 0 — G2 accuracy gate for the candidate relative-time resolver.

Loads ``tests/fixtures/commitment/relative_time_corpus.jsonl`` (semantic ground
truth, NOT generated by the resolver), runs
``safety.commitment.resolve_remind`` over every case, and classifies:

  - CORRECT       — decision matches AND (if allow) fire_at matches (±1s)
  - FALSE_ALLOW   — resolver allowed when it should clarify, OR allowed with a
                    wrong fire_at, OR overwrote a belief. DANGEROUS (incident class).
  - FALSE_CLARIFY — resolver clarified when it should allow. Annoying, not dangerous.

The G2 gate (plan §R2.1): on the held-out GOLDEN split, FALSE_ALLOW == 0.
False-clarify is reported as a rate (operating point) but is not a hard gate
until the ROC is reviewed (§R2.7).

If G2 fails (false-allow > 0 on goldens, or operationally-unacceptable
false-clarify), plan §R2.2 triggers a structured-args re-baseline BEFORE
Phase 2 — this test turning red is the signal.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import pytest

CORPUS = Path(__file__).parent / "fixtures" / "commitment" / "relative_time_corpus.jsonl"
FIRE_TOLERANCE_SECONDS = 1.0


def load_corpus() -> list[dict]:
    with CORPUS.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def _resolve(case: dict):
    from kazma_core.safety.commitment import resolve_remind

    request_at = datetime.fromisoformat(case["request_at"])
    return resolve_remind(
        case["text"], request_at=request_at, memory_beliefs=case.get("memory", []),
    )


def classify(case: dict) -> str:
    """Return CORRECT | FALSE_ALLOW | FALSE_CLARIFY for one case."""
    exp = case["expected"]
    res = _resolve(case)

    if res.overwrite_belief:
        return "FALSE_ALLOW"  # resolver must never overwrite (plan §3.6)

    exp_decision = exp["decision"]
    got_decision = res.decision

    if exp_decision == "clarify":
        return "CORRECT" if got_decision == "clarify" else "FALSE_ALLOW"

    # expected allow
    if got_decision != "allow":
        return "FALSE_CLARIFY"
    # both allow → compare fire_at
    exp_fire = exp.get("fire_at_iso")
    if exp_fire is None:
        return "FALSE_ALLOW"  # expected allow must have a fire_at
    exp_dt = datetime.fromisoformat(exp_fire)
    got_dt = res.fire_at
    if got_dt is None:
        return "FALSE_ALLOW"
    if abs((got_dt - exp_dt).total_seconds()) > FIRE_TOLERANCE_SECONDS:
        return "FALSE_ALLOW"  # wrong schedule = incident class
    return "CORRECT"


def measure(split: str | None = None) -> dict:
    """Run the resolver over the corpus (or one split) and tally outcomes."""
    cases = [c for c in load_corpus() if split is None or c["split"] == split]
    tally = {"CORRECT": 0, "FALSE_ALLOW": 0, "FALSE_CLARIFY": 0}
    by_cat: dict[str, dict[str, int]] = {}
    false_allow_cases: list[dict] = []
    false_clarify_cases: list[dict] = []
    for c in cases:
        label = classify(c)
        tally[label] += 1
        cat = c["category"]
        by_cat.setdefault(cat, {"CORRECT": 0, "FALSE_ALLOW": 0, "FALSE_CLARIFY": 0})
        by_cat[cat][label] += 1
        if label == "FALSE_ALLOW":
            false_allow_cases.append(c)
        elif label == "FALSE_CLARIFY":
            false_clarify_cases.append(c)
    n = len(cases)
    return {
        "split": split or "all",
        "n": n,
        "tally": tally,
        "accuracy": (tally["CORRECT"] / n) if n else 0.0,
        "false_allow_rate": (tally["FALSE_ALLOW"] / n) if n else 0.0,
        "false_clarify_rate": (tally["FALSE_CLARIFY"] / n) if n else 0.0,
        "by_category": by_cat,
        "false_allow_cases": false_allow_cases,
        "false_clarify_cases": false_clarify_cases,
    }


def _format_report(m: dict) -> str:
    lines = [
        f"=== G2 report — split={m['split']}  n={m['n']} ===",
        f"  accuracy        : {m['accuracy']*100:.1f}%",
        f"  FALSE_ALLOW     : {m['tally']['FALSE_ALLOW']}  ({m['false_allow_rate']*100:.1f}%)  [dangerous]",
        f"  FALSE_CLARIFY   : {m['tally']['FALSE_CLARIFY']}  ({m['false_clarify_rate']*100:.1f}%)  [annoying]",
        "  by category:",
    ]
    for cat, t in sorted(m["by_category"].items()):
        lines.append(f"    {cat:32s} ok={t['CORRECT']:3d}  FA={t['FALSE_ALLOW']:3d}  FC={t['FALSE_CLARIFY']:3d}")
    return "\n".join(lines)


# ── public report (run: pytest tests/test_commitment_corpus.py -s) ──────────

def test_g2_report_all_and_golden(capsys):
    """Print the G2 report for all / golden / hostile splits (informational)."""
    for split in ("all", "golden", "hostile"):
        print("\n" + _format_report(measure(split)))
    captured = capsys.readouterr()
    assert "G2 report" in captured.out


def test_corpus_meets_shape_requirements():
    """§R2.3 corpus shape: ≥500 cases, ≥40% AR, golden/hostile splits present."""
    cases = load_corpus()
    assert len(cases) >= 500, f"corpus below 500 floor: {len(cases)}"
    ar = sum(1 for c in cases if c["lang"] == "ar")
    assert ar / len(cases) >= 0.40, f"AR ratio {ar/len(cases)*100:.1f}% below 40% floor"
    splits = {c["split"] for c in cases}
    assert {"golden", "hostile"}.issubset(splits)
    # every case has the required label fields
    for c in cases:
        assert c["expected"]["decision"] in ("allow", "clarify", "deny")
        assert "fire_at_iso" in c["expected"]


def test_g2_gate_golden_zero_false_allow():
    """G2 GATE (plan §R2.1): false-allow == 0 on held-out goldens.

    If this fails, §R2.2 (structured-args re-baseline) triggers before Phase 2.
    """
    m = measure("golden")
    print("\n" + _format_report(m))
    if m["tally"]["FALSE_ALLOW"] > 0:
        print("\nFALSE_ALLOW golden cases (first 10):")
        for c in m["false_allow_cases"][:10]:
            res = _resolve(c)
            print(f"  - {c['id']} [{c['category']}/{c['lang']}] "
                  f"text={c['text']!r}\n      expected={c['expected']} "
                  f"got_decision={res.decision} got_fire={res.fire_at}")
    assert m["tally"]["FALSE_ALLOW"] == 0, (
        f"G2 FAILED: {m['tally']['FALSE_ALLOW']} false-allows on golden split "
        f"— §R2.2 structured-args re-baseline required before Phase 2"
    )
