tools:
    shell:
        allow:
            - cd *
            - .venv\Scripts\python.exe *
            - head *
            - mkdir *
            - echo *
            - sleep 30
            - Select-String *
            - findstr "FAILED"
            - sleep 120
            - sleep 180
            - grep *
            - findstr *
            - pwd
            - ls
            - wc *
            - find *
            - Select-Object *
            - Get-ChildItem *
            - Where-Object { *
            - python *
