# Kazma CLI PowerShell completion
# Generated by: kazma completion powershell

Register-ArgumentCompleter -Native -CommandName kazma -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $subcommands = 'serve status help completion wizard hub docs project gateway swarm update' -split '\s+'
    $flags = '--model --provider --yolo --verbose --no-banner --help -h' -split '\s+'

    # If completing a flag (starts with -)
    if ($wordToComplete -match '^--?.*') {
        $flags | Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        return
    }

    # If the previous word is --model, complete with model names
    $tokens = $commandAst.CommandElements
    $prev = ''
    foreach ($t in $tokens) {
        if ($t.Extent.StartOffset -lt $cursorPosition) {
            $prev = $t.Value
        }
    }
    if ($prev -eq '--model') {
        $models = (kazma completion --list-models 2>$null) -split "`n"
        if (-not $models) {
            $models = @('gpt-4o', 'gpt-4o-mini', 'claude-sonnet-4', 'deepseek-chat')
        }
        $models | Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        return
    }

    # Otherwise complete subcommands
    $subcommands | Where-Object { $_ -like "$wordToComplete*" } |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
}
